import { Lab } from '../types/lab';

export const LAB_CATALOG: Lab[] = [
  {
    id: 'lab-corp-portal-01',
    slug: 'corporate-portal-config-leak',
    title: 'Acme Corp Portal — Secret Key Discovery & Administrative Bypass',
    category: 'investigation',
    appType: 'corporate_portal',
    difficulty: 'beginner',
    xp: 150,
    estimatedMinutes: 20,
    requiredSkills: ['HTTP Reconnaissance', 'Source Inspection', 'Header Analysis', 'Auth Bypass'],
    scenario:
      'Acme Global Enterprise recently upgraded their internal employee portal. Security auditors suspect that developer debug flags and environment secrets were accidentally compiled into public static bundles and exposed via administrative GraphQL/REST endpoints.',
    objectives: [
      'Perform HTTP reconnaissance on the corporate intranet portal',
      'Inspect public static assets and API metadata for leaked credentials',
      'Locate the secret JWT signing key or admin API key hidden in the portal debug logs',
      'Exfiltrate the flag from the executive vault document archive'
    ],
    status: 'published',
    version: '1.4.0',
    authorName: 'Senior SecOps Lead',
    updatedAt: '2026-08-01T12:00:00Z',
    flags: [
      {
        id: 'flag-corp-1',
        title: 'Exfiltrate Executive Vault Flag',
        flagValue: 'WEBFORGE{corp_portal_jwt_secret_revealed_9942}',
        points: 150,
        description: 'Submit the master secret flag retrieved from the Acme Executive Vault.'
      }
    ],
    hints: [
      {
        id: 'hint-corp-1',
        type: 'observation',
        title: 'Observation Hint',
        content: 'Check the Developer Tools Network tab or application source files for comments containing `.env` strings or `/api/v1/debug` endpoints.',
        costXP: 0
      },
      {
        id: 'hint-corp-2',
        type: 'reasoning',
        title: 'Reasoning Hint',
        content: 'Developers often leave `/api/internal/config` or `/env` exposed in staging builds. Look for API routes returning JSON configurations.',
        costXP: 10
      },
      {
        id: 'hint-corp-3',
        type: 'method',
        title: 'Method Hint',
        content: 'Use the integrated Terminal to curl `/api/corp/config` or query `/api/corp/documents?role=admin`.',
        costXP: 15
      },
      {
        id: 'hint-corp-4',
        type: 'tool',
        title: 'Tool Hint',
        content: 'In the live app browser, switch to the "System Settings" page or click "Inspect API" to inspect responses.',
        costXP: 20
      },
      {
        id: 'hint-corp-5',
        type: 'final',
        title: 'Final Hint',
        content: 'Change the role in the portal top-bar from "employee" to "executive" or view the document labeled "Vault Archive Q3".',
        costXP: 25
      }
    ],
    writeup: {
      investigation: 'Inspected network traffic generated by the Acme Corporate Portal frontend. Noticed an unauthenticated REST request to `/api/corp/system-info` returning JSON metadata.',
      discovery: 'The JSON payload included `"JWT_SECRET": "acme_super_secret_key_2026"` and listed an restricted endpoint `/api/corp/documents?vault=true`.',
      reasoning: 'Because administrative endpoints rely on client-asserted role headers (`X-User-Role: executive`), passing this header grants access to confidential documents.',
      exploitation: 'Sent a GET request to `/api/corp/documents` with header `X-User-Role: executive`. The response yielded document #804 containing the secret flag.',
      codeSnippet: 'curl -H "X-User-Role: executive" https://corp-portal.local/api/corp/documents?vault=true',
      mitigation: 'Remove debug endpoints from production builds. Implement server-side JWT verification instead of trusting client headers.'
    },
    dockerConfig: {
      containers: [
        {
          name: 'acme-portal-web',
          image: 'webforge/acme-portal:v1.4',
          port: 8080,
          status: 'healthy',
          cpuUsage: 0.8,
          memoryUsage: 42,
          healthCheckPassed: true,
          logs: ['[INFO] Acme Corp Portal v1.4 started on port 8080', '[DEBUG] Loaded environment configuration']
        }
      ],
      networkName: 'acme-corp-net',
      healthChecks: [{ serviceName: 'acme-portal-web', endpoint: '/health', expectedStatus: 200 }],
      dependencies: ['node:20-alpine', 'express:4.21'],
      resetStrategy: 'reseed_db'
    },
    validation: {
      applicationLoads: true,
      routesExist: true,
      databaseSeeded: true,
      authenticationWorks: true,
      sessionsWork: true,
      apiWorks: true,
      assetsLoad: true,
      flagsReachable: true,
      hintsAvailable: true,
      writeupsLinked: true,
      resetWorks: true,
      noRuntimeErrors: true,
      lastTestedAt: '2026-08-08T20:00:00Z'
    },
    analytics: {
      completionsCount: 1420,
      avgTimeMinutes: 14,
      resetCount: 88,
      passRatePercentage: 94.2,
      totalSubmissions: 1510
    },
    assets: [
      {
        id: 'asset-1',
        name: 'portal-config.json',
        size: '1.2 KB',
        type: 'json',
        content: '{\n  "appName": "Acme Corporate Portal",\n  "env": "production-debug",\n  "apiVersion": "v1.4",\n  "vaultAccess": true\n}',
        description: 'Exported JSON configuration file from portal build'
      }
    ]
  },
  {
    id: 'lab-bank-dash-02',
    slug: 'apex-bank-idor-transfer',
    title: 'Apex Global Bank — IDOR Funds Transfer & Ledger Manipulation',
    category: 'api',
    appType: 'bank_dashboard',
    difficulty: 'intermediate',
    xp: 250,
    estimatedMinutes: 30,
    requiredSkills: ['API Security', 'Insecure Direct Object Reference (IDOR)', 'JSON Request Tampering'],
    scenario:
      'Apex Bank offers an online banking portal for high-net-worth clients. Threat intelligence reports suggest that the transaction API `/api/bank/transfer` trusts the sender account parameter sent in JSON bodies without verifying JWT owner claims.',
    objectives: [
      'Log into the Apex Bank dashboard as User A (Account #ACC-1001)',
      'Analyze the JSON structure sent when making a wire transfer',
      'Exploit the Insecure Direct Object Reference (IDOR) by modifying `fromAccountId` to drain target Account #ACC-9999',
      'Retrieve the flag from the administrator transfer receipt log'
    ],
    status: 'published',
    version: '2.1.0',
    authorName: 'FinTech RedTeam Lead',
    updatedAt: '2026-08-03T14:30:00Z',
    flags: [
      {
        id: 'flag-bank-1',
        title: 'Exfiltrate Vault Account Flag',
        flagValue: 'WEBFORGE{idor_bank_transfer_ledger_manipulated_7831}',
        points: 250,
        description: 'Submit the flag returned in the transaction receipt after executing the IDOR transfer.'
      }
    ],
    hints: [
      {
        id: 'hint-bank-1',
        type: 'observation',
        title: 'Observation Hint',
        content: 'Observe the transfer request body: `{ "fromAccount": "ACC-1001", "toAccount": "ACC-2002", "amount": 500 }`.',
        costXP: 0
      },
      {
        id: 'hint-bank-2',
        type: 'reasoning',
        title: 'Reasoning Hint',
        content: 'Does the server check if the logged-in user actually owns `fromAccount`? What happens if you specify `ACC-9999`?',
        costXP: 10
      },
      {
        id: 'hint-bank-3',
        type: 'method',
        title: 'Method Hint',
        content: 'In the Bank Dashboard, open the Transfer modal. Modify the From Account input or use the API Tester to send a custom JSON payload.',
        costXP: 15
      },
      {
        id: 'hint-bank-4',
        type: 'tool',
        title: 'Tool Hint',
        content: 'Target Account `#ACC-9999` belongs to Apex Reserve Vault. Transfer $10,000 to your account (`ACC-1001`).',
        costXP: 20
      },
      {
        id: 'hint-bank-5',
        type: 'final',
        title: 'Final Hint',
        content: 'Execute POST `/api/bank/transfer` with `{ "fromAccount": "ACC-9999", "toAccount": "ACC-1001", "amount": 10000 }`. The flag is in the receipt.',
        costXP: 25
      }
    ],
    writeup: {
      investigation: 'Inspected the API traffic during a standard transfer. The backend accepts `fromAccount` directly from user input.',
      discovery: 'The endpoint `/api/bank/transfer` performs no authorization check mapping `req.user.accountId` to `req.body.fromAccount`.',
      reasoning: 'An attacker can impersonate any bank account (including administrative vault accounts) simply by changing the parameter.',
      exploitation: 'Sent a tampered POST payload setting `fromAccount` to `ACC-9999` and `toAccount` to `ACC-1001`. The transaction completed successfully, returning the flag.',
      codeSnippet: 'POST /api/bank/transfer\nContent-Type: application/json\n\n{"fromAccount": "ACC-9999", "toAccount": "ACC-1001", "amount": 10000}',
      mitigation: 'Bind session identity to database queries. Never allow the client to specify the source account ID in financial transactions.'
    },
    dockerConfig: {
      containers: [
        {
          name: 'apex-bank-api',
          image: 'webforge/apex-bank:v2.1',
          port: 8081,
          status: 'healthy',
          cpuUsage: 1.1,
          memoryUsage: 58,
          healthCheckPassed: true,
          logs: ['[INFO] Apex Banking Core started', '[INFO] Ledger seeded with 5,000 mock accounts']
        }
      ],
      networkName: 'apex-bank-net',
      healthChecks: [{ serviceName: 'apex-bank-api', endpoint: '/api/bank/health', expectedStatus: 200 }],
      dependencies: ['postgres:15-alpine', 'express:4.21'],
      resetStrategy: 'fast_rollback'
    },
    validation: {
      applicationLoads: true,
      routesExist: true,
      databaseSeeded: true,
      authenticationWorks: true,
      sessionsWork: true,
      apiWorks: true,
      assetsLoad: true,
      flagsReachable: true,
      hintsAvailable: true,
      writeupsLinked: true,
      resetWorks: true,
      noRuntimeErrors: true,
      lastTestedAt: '2026-08-08T20:00:00Z'
    },
    analytics: {
      completionsCount: 980,
      avgTimeMinutes: 22,
      resetCount: 45,
      passRatePercentage: 91.5,
      totalSubmissions: 1070
    },
    assets: [
      {
        id: 'asset-2',
        name: 'apex-ledger-sample.sql',
        size: '3.4 KB',
        type: 'sql',
        content: 'INSERT INTO accounts (id, owner, balance) VALUES (\'ACC-9999\', \'Reserve Vault\', 5000000.00);',
        description: 'Sample database schema dump for Apex Ledger'
      }
    ]
  },
  {
    id: 'lab-hospital-03',
    slug: 'medtech-ehrs-sql-injection',
    title: 'MedTech Hospital System — EHR Patient Database SQL Injection',
    category: 'scenario',
    appType: 'hospital_system',
    difficulty: 'intermediate',
    xp: 300,
    estimatedMinutes: 35,
    requiredSkills: ['SQL Injection', 'Database Exploitation', 'Sanitization Bypass'],
    scenario:
      'MedTech Regional Health Network manages electronic health records (EHR) for over 50,000 patients. A search filter on the patient directory page concatenates un-sanitized user strings directly into SQL queries.',
    objectives: [
      'Access the MedTech Hospital System Doctor Portal',
      'Navigate to Patient Search',
      'Inject SQL payloads into the search bar to bypass input validation',
      'Extract the confidential VIP Patient Record containing the flag'
    ],
    status: 'published',
    version: '1.2.0',
    authorName: 'HealthSec Researcher',
    updatedAt: '2026-08-04T09:15:00Z',
    flags: [
      {
        id: 'flag-hospital-1',
        title: 'Extract VIP Patient EHR Flag',
        flagValue: 'WEBFORGE{sqli_hospital_patient_ehr_extracted_8812}',
        points: 300,
        description: 'Extract the flag stored inside the notes column of patient ID #999.'
      }
    ],
    hints: [
      {
        id: 'hint-hosp-1',
        type: 'observation',
        title: 'Observation Hint',
        content: 'Try searching for single quotes like `Smith\'` in the Patient Search box to observe if an SQL syntax error is returned.',
        costXP: 0
      },
      {
        id: 'hint-hosp-2',
        type: 'reasoning',
        title: 'Reasoning Hint',
        content: 'Use an OR condition such as `\' OR \'1\'=\'1` to return all patient rows regardless of name filtering.',
        costXP: 10
      },
      {
        id: 'hint-hosp-3',
        type: 'method',
        title: 'Method Hint',
        content: 'Use a UNION SELECT query to combine patient search results with data from the `vip_patients` table.',
        costXP: 15
      },
      {
        id: 'hint-hosp-4',
        type: 'tool',
        title: 'Tool Hint',
        content: 'Type `\' UNION SELECT 1, name, notes, 4 FROM vip_patients--` into the search box.',
        costXP: 20
      },
      {
        id: 'hint-hosp-5',
        type: 'final',
        title: 'Final Hint',
        content: 'The search string `\' OR id=999--` instantly reveals the VIP record for Patient ID 999 with the flag in clinical notes.',
        costXP: 25
      }
    ],
    writeup: {
      investigation: 'Tested input validation on `/api/hospital/patients?search=test`. Submitting a single quote triggered an SQLite exception.',
      discovery: 'The server executes `SELECT id, name, condition, notes FROM patients WHERE name LIKE \'%\' + search + \'%\'`.',
      reasoning: 'Unescaped SQL string concatenation allows arbitrary SQL commands to be appended.',
      exploitation: 'Entered `\' OR id=999--` into the search field. The query returned patient #999 (Governor Smith), displaying the flag in the clinical summary notes.',
      codeSnippet: "SELECT * FROM patients WHERE name LIKE '' OR id=999--%'",
      mitigation: 'Use parameterized queries (prepared statements) with ORM placeholders or `$1` parameter bindings.'
    },
    dockerConfig: {
      containers: [
        {
          name: 'medtech-ehr-app',
          image: 'webforge/medtech-ehr:v1.2',
          port: 8082,
          status: 'healthy',
          cpuUsage: 0.9,
          memoryUsage: 48,
          healthCheckPassed: true,
          logs: ['[INFO] MedTech EHR Portal initialized', '[INFO] SQLite database locked in read-only mode']
        }
      ],
      networkName: 'medtech-net',
      healthChecks: [{ serviceName: 'medtech-ehr-app', endpoint: '/health', expectedStatus: 200 }],
      dependencies: ['sqlite3', 'express:4.21'],
      resetStrategy: 'reseed_db'
    },
    validation: {
      applicationLoads: true,
      routesExist: true,
      databaseSeeded: true,
      authenticationWorks: true,
      sessionsWork: true,
      apiWorks: true,
      assetsLoad: true,
      flagsReachable: true,
      hintsAvailable: true,
      writeupsLinked: true,
      resetWorks: true,
      noRuntimeErrors: true,
      lastTestedAt: '2026-08-08T20:00:00Z'
    },
    analytics: {
      completionsCount: 810,
      avgTimeMinutes: 28,
      resetCount: 31,
      passRatePercentage: 88.4,
      totalSubmissions: 916
    },
    assets: [
      {
        id: 'asset-3',
        name: 'hl7-patient-schema.json',
        size: '2.1 KB',
        type: 'json',
        content: '{\n  "resourceType": "Patient",\n  "id": "999",\n  "classification": "RESTRICTED_VIP"\n}',
        description: 'HL7 FHIR JSON record format specification'
      }
    ]
  },
  {
    id: 'lab-lms-04',
    slug: 'forge-lms-file-upload-xss',
    title: 'Forge LMS — Unrestricted Assignment Upload & Stored XSS',
    category: 'guided',
    appType: 'learning_management',
    difficulty: 'beginner',
    xp: 180,
    estimatedMinutes: 25,
    requiredSkills: ['File Upload Security', 'Cross-Site Scripting (XSS)', 'MIME Validation'],
    scenario:
      'Forge Learning Management System allows students to submit assignment PDF/ZIP files. The file processor fails to sanitize HTML contents inside SVG/HTML uploads, allowing stored XSS execution in the instructor grading interface.',
    objectives: [
      'Navigate to the Student Portal Assignment Submission page',
      'Craft an HTML/SVG payload containing an XSS execution trigger',
      'Upload the file as an assignment submission',
      'Trigger administrative session evaluation to capture the instructor flag'
    ],
    status: 'published',
    version: '1.1.0',
    authorName: 'EdTech Security Lead',
    updatedAt: '2026-08-05T11:20:00Z',
    flags: [
      {
        id: 'flag-lms-1',
        title: 'Exfiltrate Instructor Session Flag',
        flagValue: 'WEBFORGE{stored_xss_lms_assignment_payload_4410}',
        points: 180,
        description: 'Submit the flag executed during the instructor grade review cycle.'
      }
    ],
    hints: [
      {
        id: 'hint-lms-1',
        type: 'observation',
        title: 'Observation Hint',
        content: 'Notice that the assignment uploader accepts `.svg` files and renders them inline on the grading review screen.',
        costXP: 0
      },
      {
        id: 'hint-lms-2',
        type: 'reasoning',
        title: 'Reasoning Hint',
        content: 'An SVG image can contain `<script>` tags. When rendered directly by a browser, JavaScript executes in the viewer context.',
        costXP: 10
      },
      {
        id: 'hint-lms-3',
        type: 'method',
        title: 'Method Hint',
        content: 'Upload a file named `solution.svg` containing `<svg xmlns="http://www.w3.org/2000/svg"><script>window.getLmsFlag()</script></svg>`.',
        costXP: 15
      },
      {
        id: 'hint-lms-4',
        type: 'tool',
        title: 'Tool Hint',
        content: 'Click the "Simulate Instructor Review" button after uploading your file to trigger execution.',
        costXP: 20
      },
      {
        id: 'hint-lms-5',
        type: 'final',
        title: 'Final Hint',
        content: 'The instructor script evaluates submitted attachments. The XSS payload triggers `window.getLmsFlag()`, revealing `WEBFORGE{stored_xss_lms_assignment_payload_4410}`.',
        costXP: 25
      }
    ],
    writeup: {
      investigation: 'Tested the file submission route `/api/lms/upload`. Observed that uploaded SVG files were served with `Content-Type: image/svg+xml`.',
      discovery: 'SVG vector files are XML based and execute nested JavaScript when viewed directly in the DOM.',
      reasoning: 'Lacking `Content-Disposition: attachment` or a Content Security Policy (CSP), the instructor browser executes attacker code upon opening the submission.',
      exploitation: 'Uploaded an SVG payload calling the instructor session vault. When the instructor reviewed the assignment, the payload exfiltrated the flag.',
      codeSnippet: '<svg xmlns="http://www.w3.org/2000/svg"><script>alert(document.cookie);</script></svg>',
      mitigation: 'Enforce strong Content-Disposition headers, sanitize uploaded files, and serve user assets from an isolated sandbox domain.'
    },
    dockerConfig: {
      containers: [
        {
          name: 'forge-lms-app',
          image: 'webforge/lms:v1.1',
          port: 8083,
          status: 'healthy',
          cpuUsage: 0.7,
          memoryUsage: 38,
          healthCheckPassed: true,
          logs: ['[INFO] Forge LMS initialized', '[INFO] Instructor grading queue listening...']
        }
      ],
      networkName: 'lms-net',
      healthChecks: [{ serviceName: 'forge-lms-app', endpoint: '/health', expectedStatus: 200 }],
      dependencies: ['node:20-alpine'],
      resetStrategy: 'fast_rollback'
    },
    validation: {
      applicationLoads: true,
      routesExist: true,
      databaseSeeded: true,
      authenticationWorks: true,
      sessionsWork: true,
      apiWorks: true,
      assetsLoad: true,
      flagsReachable: true,
      hintsAvailable: true,
      writeupsLinked: true,
      resetWorks: true,
      noRuntimeErrors: true,
      lastTestedAt: '2026-08-08T20:00:00Z'
    },
    analytics: {
      completionsCount: 1150,
      avgTimeMinutes: 18,
      resetCount: 22,
      passRatePercentage: 96.1,
      totalSubmissions: 1196
    },
    assets: []
  },
  {
    id: 'lab-ecom-05',
    slug: 'shopmax-price-tampering',
    title: 'ShopMax E-Commerce — Client-Side Price Tampering & Cart Exploitation',
    category: 'practice',
    appType: 'ecommerce_platform',
    difficulty: 'beginner',
    xp: 200,
    estimatedMinutes: 20,
    requiredSkills: ['HTTP Interception', 'Business Logic Exploitation', 'Cart Manipulation'],
    scenario:
      'ShopMax is a major online retailer. Due to a flaw in their checkout API, the order total and unit prices are accepted directly from the client request payload without verifying product prices on the server.',
    objectives: [
      'Add a $2,500 High-End Gaming Workstation to your ShopMax Shopping Cart',
      'Proceed to checkout and intercept or inspect the POST payload sent to `/api/ecommerce/checkout`',
      'Tamper with the `price` parameter, changing $2,500 to $0.01',
      'Complete the order to receive the VIP purchase receipt flag'
    ],
    status: 'published',
    version: '1.3.0',
    authorName: 'ECom Auditor',
    updatedAt: '2026-08-06T15:00:00Z',
    flags: [
      {
        id: 'flag-ecom-1',
        title: 'Complete Tampered Order Flag',
        flagValue: 'WEBFORGE{ecommerce_price_tampered_checkout_success_1029}',
        points: 200,
        description: 'Submit the flag generated upon completing a tampered checkout order for under $1.00.'
      }
    ],
    hints: [
      {
        id: 'hint-ecom-1',
        type: 'observation',
        title: 'Observation Hint',
        content: 'Look at the checkout payload in the DevTools Network panel. Notice how `items: [{ id: "ITEM-99", price: 2500 }]` is sent from the browser.',
        costXP: 0
      },
      {
        id: 'hint-ecom-2',
        type: 'reasoning',
        title: 'Reasoning Hint',
        content: 'Never trust price values supplied by the frontend client. The server should query item prices from its internal database.',
        costXP: 10
      },
      {
        id: 'hint-ecom-3',
        type: 'method',
        title: 'Method Hint',
        content: 'In the ShopMax checkout interface, click "Tamper Request Payload" or use the API tester to submit `{ "price": 0.01 }`.',
        costXP: 15
      },
      {
        id: 'hint-ecom-4',
        type: 'tool',
        title: 'Tool Hint',
        content: 'Change the total parameter or unit price to 0.01 in the checkout form.',
        costXP: 20
      },
      {
        id: 'hint-ecom-5',
        type: 'final',
        title: 'Final Hint',
        content: 'Submit checkout with unit price 0.01 for ITEM-99. The order succeeds and prints the flag on the confirmation invoice.',
        costXP: 25
      }
    ],
    writeup: {
      investigation: 'Monitored the POST request sent when placing an order on ShopMax.',
      discovery: 'The client sends JSON containing `itemPrice: 2500.00` and `totalAmount: 2500.00`. The server blindly processes payments using the submitted total.',
      reasoning: 'Manipulating client-controlled financial values allows attackers to purchase items for arbitrary prices.',
      exploitation: 'Modified `itemPrice` to `0.01`. The payment gateway accepted $0.01 and marked the order as PAID, displaying the confirmation flag.',
      codeSnippet: 'POST /api/ecommerce/checkout\n{"cartId": "C-992", "items": [{"id": "ITEM-99", "price": 0.01}]}',
      mitigation: 'Recalculate order totals on the server by looking up authoritative item prices in the database.'
    },
    dockerConfig: {
      containers: [
        {
          name: 'shopmax-store',
          image: 'webforge/shopmax:v1.3',
          port: 8084,
          status: 'healthy',
          cpuUsage: 1.0,
          memoryUsage: 50,
          healthCheckPassed: true,
          logs: ['[INFO] ShopMax E-Commerce Engine running', '[INFO] Payment gateway connected in sandbox mode']
        }
      ],
      networkName: 'shopmax-net',
      healthChecks: [{ serviceName: 'shopmax-store', endpoint: '/health', expectedStatus: 200 }],
      dependencies: ['node:20-alpine'],
      resetStrategy: 'fast_rollback'
    },
    validation: {
      applicationLoads: true,
      routesExist: true,
      databaseSeeded: true,
      authenticationWorks: true,
      sessionsWork: true,
      apiWorks: true,
      assetsLoad: true,
      flagsReachable: true,
      hintsAvailable: true,
      writeupsLinked: true,
      resetWorks: true,
      noRuntimeErrors: true,
      lastTestedAt: '2026-08-08T20:00:00Z'
    },
    analytics: {
      completionsCount: 1650,
      avgTimeMinutes: 12,
      resetCount: 19,
      passRatePercentage: 98.2,
      totalSubmissions: 1680
    },
    assets: []
  },
  {
    id: 'lab-cloud-06',
    slug: 'skywall-cloud-metadata-ssrf',
    title: 'SkyWall Cloud Dashboard — SSRF & AWS Metadata Key Extraction',
    category: 'boss',
    appType: 'cloud_dashboard',
    difficulty: 'advanced',
    xp: 500,
    estimatedMinutes: 45,
    requiredSkills: ['Server-Side Request Forgery (SSRF)', 'Cloud Metadata Analysis', 'IAM Escalation'],
    scenario:
      'SkyWall Cloud Console features a custom "Web Page Screenshot & Status Checker" service. By supplying an external URL, users can trigger the backend container to issue HTTP GET requests on their behalf.',
    objectives: [
      'Access the SkyWall Cloud Dashboard',
      'Navigate to the URL Health Inspector utility',
      'Exploit Server-Side Request Forgery (SSRF) to query internal AWS IMDS metadata endpoint (`http://169.254.169.254/latest/meta-data/`)',
      'Exfiltrate the temporary IAM Role credentials and retrieve the secret S3 master flag'
    ],
    status: 'published',
    version: '2.0.0',
    authorName: 'Cloud Security Architect',
    updatedAt: '2026-08-07T16:45:00Z',
    flags: [
      {
        id: 'flag-cloud-1',
        title: 'Exfiltrate IAM Cloud Master Flag',
        flagValue: 'WEBFORGE{ssrf_cloud_metadata_iam_keys_compromised_9091}',
        points: 500,
        description: 'Submit the master flag retrieved from the simulated cloud metadata IAM role.'
      }
    ],
    hints: [
      {
        id: 'hint-cloud-1',
        type: 'observation',
        title: 'Observation Hint',
        content: 'The URL status checker accepts `http://` inputs and fetches their responses server-side.',
        costXP: 0
      },
      {
        id: 'hint-cloud-2',
        type: 'reasoning',
        title: 'Reasoning Hint',
        content: 'Cloud environments (AWS, GCP, Azure) host a local instance metadata service at `169.254.169.254`.',
        costXP: 10
      },
      {
        id: 'hint-cloud-3',
        type: 'method',
        title: 'Method Hint',
        content: 'Input `http://169.254.169.254/latest/meta-data/iam/security-credentials/SkyWallRole` into the checker.',
        costXP: 15
      },
      {
        id: 'hint-cloud-4',
        type: 'tool',
        title: 'Tool Hint',
        content: 'In the Cloud Console URL field, submit the metadata path or use the internal terminal curl command.',
        costXP: 20
      },
      {
        id: 'hint-cloud-5',
        type: 'final',
        title: 'Final Hint',
        content: 'Fetching `http://169.254.169.254/latest/meta-data/iam/security-credentials/admin-role` returns the secret key containing `WEBFORGE{ssrf_cloud_metadata_iam_keys_compromised_9091}`.',
        costXP: 25
      }
    ],
    writeup: {
      investigation: 'Identified an SSRF vector in `/api/cloud/fetch-url`. The application takes a target URL parameter and executes an outbound request.',
      discovery: 'The server does not enforce IP blacklisting or block internal link-local addresses (`169.254.0.0/16`).',
      reasoning: 'Requesting the cloud metadata endpoint allows an unauthenticated user to dump sensitive IAM credentials assigned to the host instance.',
      exploitation: 'Submitted `http://169.254.169.254/latest/meta-data/iam/security-credentials/admin-role`. The server returned JSON containing AWS access keys and the flag.',
      codeSnippet: 'POST /api/cloud/fetch-url\n{"url": "http://169.254.169.254/latest/meta-data/iam/security-credentials/admin-role"}',
      mitigation: 'Require IMDSv2 with Session Tokens, whitelist allowed external domains, and restrict link-local IP routing.'
    },
    dockerConfig: {
      containers: [
        {
          name: 'skywall-cloud-node',
          image: 'webforge/skywall-cloud:v2.0',
          port: 8085,
          status: 'healthy',
          cpuUsage: 1.4,
          memoryUsage: 68,
          healthCheckPassed: true,
          logs: ['[INFO] SkyWall Cloud Console running', '[INFO] IMDS simulation service listening on 169.254.169.254']
        }
      ],
      networkName: 'skywall-net',
      healthChecks: [{ serviceName: 'skywall-cloud-node', endpoint: '/health', expectedStatus: 200 }],
      dependencies: ['node:20-alpine'],
      resetStrategy: 'cold_reboot'
    },
    validation: {
      applicationLoads: true,
      routesExist: true,
      databaseSeeded: true,
      authenticationWorks: true,
      sessionsWork: true,
      apiWorks: true,
      assetsLoad: true,
      flagsReachable: true,
      hintsAvailable: true,
      writeupsLinked: true,
      resetWorks: true,
      noRuntimeErrors: true,
      lastTestedAt: '2026-08-08T20:00:00Z'
    },
    analytics: {
      completionsCount: 520,
      avgTimeMinutes: 38,
      resetCount: 64,
      passRatePercentage: 79.8,
      totalSubmissions: 652
    },
    assets: []
  },
  {
    id: 'lab-git-07',
    slug: 'gitrepo-exposed-dotgit-secrets',
    title: 'CodeForge Git — Exposed .git Repository & Commit History Analysis',
    category: 'discovery',
    appType: 'git_repository',
    difficulty: 'beginner',
    xp: 170,
    estimatedMinutes: 20,
    requiredSkills: ['Git Forensics', 'Exposed .git Extraction', 'Commit Analysis'],
    scenario:
      'A web application developer accidentally published the `.git` directory onto the live public document root at CodeForge Repositories. Former commits contained hardcoded database passwords.',
    objectives: [
      'Access the CodeForge Git Web Repository',
      'Inspect the public file structure for an exposed `.git` directory',
      'Use Git commit log inspection to review historical commit diffs',
      'Locate the deleted hardcoded secret token in commit `#c4a921`'
    ],
    status: 'published',
    version: '1.0.0',
    authorName: 'Git Forensics Team',
    updatedAt: '2026-08-02T10:00:00Z',
    flags: [
      {
        id: 'flag-git-1',
        title: 'Extract Recovered Git Secret Flag',
        flagValue: 'WEBFORGE{exposed_git_commit_history_hardcoded_pass_3301}',
        points: 170,
        description: 'Submit the hardcoded secret password recovered from the historical git commit diff.'
      }
    ],
    hints: [
      {
        id: 'hint-git-1',
        type: 'observation',
        title: 'Observation Hint',
        content: 'Check the repository commit history tab or query `/api/git/history`.',
        costXP: 0
      },
      {
        id: 'hint-git-2',
        type: 'reasoning',
        title: 'Reasoning Hint',
        content: 'Developers often delete hardcoded passwords in later commits, but Git preserves every historical commit object forever unless purged.',
        costXP: 10
      },
      {
        id: 'hint-git-3',
        type: 'method',
        title: 'Method Hint',
        content: 'Click on Commit `#c4a921` labeled "Remove hardcoded credentials from config.js".',
        costXP: 15
      },
      {
        id: 'hint-git-4',
        type: 'tool',
        title: 'Tool Hint',
        content: 'In the terminal, run `git log -p` or view the diff preview in the UI commit log tab.',
        costXP: 20
      },
      {
        id: 'hint-git-5',
        type: 'final',
        title: 'Final Hint',
        content: 'The diff line `- const DB_PASS = "WEBFORGE{exposed_git_commit_history_hardcoded_pass_3301}"` holds the flag.',
        costXP: 25
      }
    ],
    writeup: {
      investigation: 'Browsed the CodeForge Repository website and noticed commit history was accessible.',
      discovery: 'Inspected commit `#c4a921` titled "Cleaned up config".',
      reasoning: 'Removing sensitive text in a new commit does not remove it from Git object history.',
      exploitation: 'Inspected the commit diff and extracted the removed constant string.',
      codeSnippet: 'git log -p -1 c4a921',
      mitigation: 'Use tools like `git-filter-repo` or BFG Repo-Cleaner to permanently scrub secrets from repository history before pushing.'
    },
    dockerConfig: {
      containers: [
        {
          name: 'codeforge-git-server',
          image: 'webforge/codeforge:v1.0',
          port: 8086,
          status: 'healthy',
          cpuUsage: 0.5,
          memoryUsage: 32,
          healthCheckPassed: true,
          logs: ['[INFO] CodeForge Git Server active']
        }
      ],
      networkName: 'codeforge-net',
      healthChecks: [{ serviceName: 'codeforge-git-server', endpoint: '/health', expectedStatus: 200 }],
      dependencies: ['git', 'node:20-alpine'],
      resetStrategy: 'fast_rollback'
    },
    validation: {
      applicationLoads: true,
      routesExist: true,
      databaseSeeded: true,
      authenticationWorks: true,
      sessionsWork: true,
      apiWorks: true,
      assetsLoad: true,
      flagsReachable: true,
      hintsAvailable: true,
      writeupsLinked: true,
      resetWorks: true,
      noRuntimeErrors: true,
      lastTestedAt: '2026-08-08T20:00:00Z'
    },
    analytics: {
      completionsCount: 1390,
      avgTimeMinutes: 15,
      resetCount: 12,
      passRatePercentage: 97.5,
      totalSubmissions: 1425
    },
    assets: []
  },
  {
    id: 'lab-iot-08',
    slug: 'smartgrid-iot-command-injection',
    title: 'SmartGrid IoT — MQTT Firmware Update & Command Injection',
    category: 'multi_container',
    appType: 'iot_dashboard',
    difficulty: 'advanced',
    xp: 450,
    estimatedMinutes: 40,
    requiredSkills: ['Command Injection', 'IoT Protocol Inspection', 'Firmware Analysis'],
    scenario:
      'SmartGrid Power manages municipal solar micro-grids. The IoT device management console executes system ping diagnostic checks via shell commands without sanitizing IP parameters.',
    objectives: [
      'Access the SmartGrid IoT Management Portal',
      'Open the Device Diagnostics tab',
      'Inject shell command separators (e.g. `;`, `|`, `$(...)`) into the Ping IP test input',
      'Execute `cat /etc/iot_master.key` to exfiltrate the municipal grid flag'
    ],
    status: 'published',
    version: '1.5.0',
    authorName: 'IoT Security Lab',
    updatedAt: '2026-08-06T18:00:00Z',
    flags: [
      {
        id: 'flag-iot-1',
        title: 'Exfiltrate Municipal SmartGrid Flag',
        flagValue: 'WEBFORGE{iot_command_injection_ping_diag_pwned_6602}',
        points: 450,
        description: 'Submit the master flag retrieved from `/etc/iot_master.key` via command injection.'
      }
    ],
    hints: [
      {
        id: 'hint-iot-1',
        type: 'observation',
        title: 'Observation Hint',
        content: 'The ping diagnostic tool runs `ping -c 2 <user_ip>` under the hood.',
        costXP: 0
      },
      {
        id: 'hint-iot-2',
        type: 'reasoning',
        title: 'Reasoning Hint',
        content: 'Appending `; id` or `; cat /etc/iot_master.key` chains a second Linux shell command.',
        costXP: 10
      },
      {
        id: 'hint-iot-3',
        type: 'method',
        title: 'Method Hint',
        content: 'In the IP diagnostic field, enter `8.8.8.8; cat /etc/iot_master.key`.',
        costXP: 15
      },
      {
        id: 'hint-iot-4',
        type: 'tool',
        title: 'Tool Hint',
        content: 'You can also test this via the terminal or API tester endpoint `/api/iot/ping`.',
        costXP: 20
      },
      {
        id: 'hint-iot-5',
        type: 'final',
        title: 'Final Hint',
        content: 'Submitting `127.0.0.1; cat /etc/iot_master.key` outputs `WEBFORGE{iot_command_injection_ping_diag_pwned_6602}` in stdout.',
        costXP: 25
      }
    ],
    writeup: {
      investigation: 'Tested the network diagnostic ping tool on the SmartGrid dashboard.',
      discovery: 'The backend calls `exec("ping -c 2 " + req.body.host)` directly in Node.js/Python.',
      reasoning: 'Unsanitized parameters passed to system shell execute arbitrary commands with host privileges.',
      exploitation: 'Injected `8.8.8.8; cat /etc/iot_master.key`. The command output returned the key file contents containing the flag.',
      codeSnippet: 'POST /api/iot/ping\n{"host": "127.0.0.1; cat /etc/iot_master.key"}',
      mitigation: 'Avoid shell execution. Use standard network library bindings (e.g. `net.isIP()`) or sanitize parameters using strict regex.'
    },
    dockerConfig: {
      containers: [
        {
          name: 'smartgrid-iot-gateway',
          image: 'webforge/smartgrid-iot:v1.5',
          port: 8087,
          status: 'healthy',
          cpuUsage: 1.2,
          memoryUsage: 54,
          healthCheckPassed: true,
          logs: ['[INFO] SmartGrid Gateway connected to MQTT Broker', '[INFO] 12 Grid Nodes online']
        },
        {
          name: 'mqtt-broker',
          image: 'eclipse-mosquitto:latest',
          port: 1883,
          status: 'healthy',
          cpuUsage: 0.3,
          memoryUsage: 16,
          healthCheckPassed: true,
          logs: ['[INFO] Mosquitto MQTT broker listening on port 1883']
        }
      ],
      networkName: 'smartgrid-net',
      healthChecks: [{ serviceName: 'smartgrid-iot-gateway', endpoint: '/health', expectedStatus: 200 }],
      dependencies: ['mosquitto', 'node:20-alpine'],
      resetStrategy: 'cold_reboot'
    },
    validation: {
      applicationLoads: true,
      routesExist: true,
      databaseSeeded: true,
      authenticationWorks: true,
      sessionsWork: true,
      apiWorks: true,
      assetsLoad: true,
      flagsReachable: true,
      hintsAvailable: true,
      writeupsLinked: true,
      resetWorks: true,
      noRuntimeErrors: true,
      lastTestedAt: '2026-08-08T20:00:00Z'
    },
    analytics: {
      completionsCount: 640,
      avgTimeMinutes: 32,
      resetCount: 41,
      passRatePercentage: 84.6,
      totalSubmissions: 756
    },
    assets: []
  }
];

export function getLabById(id: string): Lab | undefined {
  return LAB_CATALOG.find((lab) => lab.id === id || lab.slug === id);
}
